-- ============================================================
-- APA-DSS: Load Synthetic Dataset
-- ============================================================
-- This is a WRAPPER script. The actual data is generated by:
--   ml-pipeline/data/generate_synthetic_data.py
--
-- To regenerate:
--   1. Run: python ml-pipeline/data/generate_synthetic_data.py
--   2. Then run this wrapper OR the generated file directly:
--      mysql -u root -p < ml-pipeline/data/synthetic_data.sql
--
-- IMPORTANT: This script only affects the following tables:
--   - student_enrollments
--   - students
--   - modules
--   - programmes
--   - faculties
--   - semesters
--
-- The `admins` table is NEVER modified. Your login remains intact.
-- ============================================================

USE student_record_system;

-- Safety: verify admins still exist before doing anything
SELECT 'Admins preserved:' AS check_name, COUNT(*) AS admin_count FROM admins;

-- The actual data operations are in synthetic_data.sql
-- Run: mysql -u root -p student_record_system < ml-pipeline/data/synthetic_data.sql